// <auto-generated />
using System;
using FDL.Infra.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FDL.Infra.Persistance.Migrations
{
    [DbContext(typeof(DomusDbContext))]
    [Migration("20260927181848_WorkflowReferenceDossier")]
    partial class WorkflowReferenceDossier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FDL.Infra.Persistance.RegistreRow", b =>
                {
                    b.Property<int>("IdRegistre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_registre");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdRegistre"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("text")
                        .HasColumnName("commentaire");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<DateTime>("DateStatut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_statut");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<int>("IdUserCreation")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_creation");

                    b.Property<int?>("IdUserUpdate")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update");

                    b.PrimitiveCollection<int[]>("ListeCommunes")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("liste_communes");

                    b.Property<int>("NbChambresMax")
                        .HasColumnType("integer")
                        .HasColumnName("nb_chambres_max");

                    b.Property<int>("NbChambresMin")
                        .HasColumnType("integer")
                        .HasColumnName("nb_chambres_min");

                    b.Property<int>("ReferenceDossier")
                        .HasColumnType("integer")
                        .HasColumnName("reference_dossier");

                    b.Property<bool>("SouhaiteAscenseur")
                        .HasColumnType("boolean")
                        .HasColumnName("souhaite_ascenseur");

                    b.Property<int>("Statut")
                        .HasColumnType("integer")
                        .HasColumnName("statut");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("IdRegistre")
                        .HasName("pk_registre");

                    b.HasIndex("ReferenceDossier")
                        .IsUnique()
                        .HasDatabaseName("ux_registre_reference_dossier");

                    b.ToTable("registre", (string)null);
                });

            modelBuilder.Entity("FDL.Infra.Persistance.WorkflowRow", b =>
                {
                    b.Property<int>("IdWorkflow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_workflow");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdWorkflow"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTime>("DateExpedition")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_expedition");

                    b.Property<DateTime?>("DateTerminaison")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_terminaison");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<int>("IdDocument")
                        .HasColumnType("integer")
                        .HasColumnName("id_document");

                    b.Property<int?>("IdGroupeAssigne")
                        .HasColumnType("integer")
                        .HasColumnName("id_groupe_assigne");

                    b.Property<int?>("IdUserAssigne")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_assigne");

                    b.Property<int>("IdUserExpediteur")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_expediteur");

                    b.Property<int?>("IdUserTerminaison")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_terminaison");

                    b.Property<int?>("IdUserUpdate")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("ReferenceDossier")
                        .HasColumnType("integer")
                        .HasColumnName("reference_dossier");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("IdWorkflow")
                        .HasName("pk_workflow");

                    b.HasIndex("IdGroupeAssigne")
                        .HasDatabaseName("ix_workflow_id_groupe_assigne")
                        .HasFilter("id_user_terminaison IS NULL");

                    b.HasIndex("IdUserAssigne")
                        .HasDatabaseName("ix_workflow_id_user_assigne")
                        .HasFilter("id_user_terminaison IS NULL");

                    b.ToTable("workflow", null, t =>
                        {
                            t.HasCheckConstraint("ck_workflow_assignation", "id_user_assigne IS NOT NULL OR id_groupe_assigne IS NOT NULL");

                            t.HasCheckConstraint("ck_workflow_document", "type <> 1 OR id_document > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
