// <auto-generated />
using System;
using FDL.Infra.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FDL.Infra.Persistance.Migrations
{
    [DbContext(typeof(DomusDbContext))]
    partial class DomusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FDL.Infra.Persistance.WorkflowRow", b =>
                {
                    b.Property<int>("IdWorkflow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_workflow");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdWorkflow"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTime>("DateExpedition")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_expedition");

                    b.Property<DateTime?>("DateTerminaison")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_terminaison");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_update");

                    b.Property<int>("IdDocument")
                        .HasColumnType("integer")
                        .HasColumnName("id_document");

                    b.Property<int?>("IdGroupeAssigne")
                        .HasColumnType("integer")
                        .HasColumnName("id_groupe_assigne");

                    b.Property<int?>("IdUserAssigne")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_assigne");

                    b.Property<int>("IdUserExpediteur")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_expediteur");

                    b.Property<int?>("IdUserTerminaison")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_terminaison");

                    b.Property<int?>("IdUserUpdate")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_update");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("NumeroDossier")
                        .HasColumnType("integer")
                        .HasColumnName("numero_dossier");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("IdWorkflow")
                        .HasName("pk_workflow");

                    b.HasIndex("IdGroupeAssigne")
                        .HasDatabaseName("ix_workflow_id_groupe_assigne")
                        .HasFilter("id_user_terminaison IS NULL");

                    b.HasIndex("IdUserAssigne")
                        .HasDatabaseName("ix_workflow_id_user_assigne")
                        .HasFilter("id_user_terminaison IS NULL");

                    b.ToTable("workflow", null, t =>
                        {
                            t.HasCheckConstraint("ck_workflow_assignation", "id_user_assigne IS NOT NULL OR id_groupe_assigne IS NOT NULL");

                            t.HasCheckConstraint("ck_workflow_document", "type <> 1 OR id_document > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
